export const MENU_CODE_LIST = {
    code: "20_overhaul",
    level: 1,
    method: "GET",
    name: "检修管理",
    showOrder: null,
    sub: [
        {
            code: "2001_deviceList",
            level: 2,
            method: "GET",
            name: "视频设备列表",
            showOrder: null,
            sub: [],
            type: 1,
            url: "/overhaul/device",
            viewPath: null
        }, {
            code: "2002_templateLib",
            level: 2,
            method: "GET",
            name: "模板库管理",
            showOrder: null,
            sub: [{
                code: "200201_safetyInstruction",
                level: 3,
                method: "GET",
                name: "安全须知模板",
                showOrder: null,
                sub: [],
                type: 1,
                url: "/overhaul/templateLib/safetyInstruction",
                viewPath: null
            },
            {
                code: "200202_doc",
                level: 3,
                method: "GET",
                name: "文档模板",
                showOrder: null,
                sub: [],
                type: 1,
                url: "/overhaul/templateLib/doc",
                viewPath: null
            },
            {
                code: "200203_deviceListTemp",
                level: 3,
                method: "GET",
                name: "设备清单模板",
                showOrder: null,
                sub: [],
                type: 1,
                url: "/overhaul/templateLib/deviceListTemp",
                viewPath: null
            },
            {
                code: "200204_bomTemp",
                level: 3,
                method: "GET",
                name: "拆解BOM模板",
                showOrder: null,
                sub: [],
                type: 1,
                url: "/overhaul/templateLib/bomTemp",
                viewPath: null
            }],
            type: 1,
            url: "/overhaul/templateLib",
            viewPath: null
        },
        {
            code: "2003_sysConfig",
            level: 2,
            method: "GET",
            name: "业务班组配置",
            showOrder: null,
            sub: [],
            type: 1,
            url: "/overhaul/sysConfig",
            viewPath: null
        }, {
            code: "2004_survey",
            level: 2,
            method: "GET",
            name: "勘察工单管理",
            showOrder: null,
            sub: [
                {
                    code: "2004_btn_add",
                    level: 3,
                    method: "GET",
                    name: "勘查工单-列表-新增按钮",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/survey",
                    viewPath: null,
                },
                {
                    code: "2004_btn_check",
                    level: 3,
                    method: "GET",
                    name: "勘查工单-列表-发起审核按钮",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/survey",
                    viewPath: null,
                },
                {
                    code: "2004_btn_del",
                    level: 3,
                    method: "GET",
                    name: "勘查工单-列表-删除按钮",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/survey",
                    viewPath: null,
                },
                {
                    code: "2004_btn_edit",
                    level: 3,
                    method: "GET",
                    name: "勘查工单-列表-编辑按钮",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/survey",
                    viewPath: null,
                },
                {
                    code: "2004_btn_pause",
                    level: 3,
                    method: "GET",
                    name: "勘查工单-列表-暂停按钮",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/survey",
                    viewPath: null,
                },
                {
                    code: "2004_btn_close",
                    level: 3,
                    method: "GET",
                    name: "勘查工单-列表-结束按钮",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/survey",
                    viewPath: null,
                },
                {
                    code: "2004_survey_appoint",
                    level: 3,
                    method: "GET",
                    name: "勘查工单-详情-工序指派按钮",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/survey",
                    viewPath: null,
                },
                {
                    code: "2004_survey_processInfo",
                    level: 3,
                    method: "GET",
                    name: "勘查工单-工序信息查看",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/survey",
                    viewPath: null,
                },
                {
                    code: "2004_survey_workInfo_check",
                    level: 3,
                    method: "GET",
                    name: "勘查工单-工序树-审核",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/survey",
                    viewPath: null,
                },
                {
                    code: "2004_survey_review",
                    level: 3,
                    method: "GET",
                    name: "勘查工单-工序复核",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/survey",
                    viewPath: null,
                }, {
                    code: "2004_survey_addIssue",
                    level: 3,
                    method: "GET",
                    name: "勘查工单-问题添加",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/survey",
                    viewPath: null,
                },
                {
                    code: "2004_survey_editContent",
                    level: 3,
                    method: "GET",
                    name: "勘查工单-工作内容编辑",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/survey",
                    viewPath: null,
                },
                {
                    code: "2004_survey_infoAppoint",
                    level: 3,
                    method: "GET",
                    name: "勘查工单-派工按钮",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/survey",
                    viewPath: null,
                },
                {
                    code: "2004_survey_orderCheck",
                    level: 3,
                    method: "GET",
                    name: "勘查工单-复核人员按钮",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/survey",
                    viewPath: null,
                },

                {
                    code: "2004_survey_issue",
                    level: 3,
                    method: "GET",
                    name: "勘查工单-问题查看",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/survey",
                    viewPath: null,
                },
                //报告：命名 2005_report_view|edit_报告的worktype
                {
                    code: "2004_report_view_1",
                    level: 3,
                    method: "GET",
                    name: "勘查工单-勘查报告-查看",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/survey",
                    viewPath: null,
                }, {
                    code: "2004_report_edit_1",
                    level: 3,
                    method: "GET",
                    name: "勘查工单-勘查报告-编辑",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/survey",
                    viewPath: null,
                }],
            type: 1,
            url: "/overhaul/survey",
            viewPath: null
        }, {
            code: "2005_overhaulOrder",
            level: 2,
            method: "GET",
            name: "检修工单管理",
            showOrder: null,
            sub: [
                {
                    code: "2005_btn_delete",
                    level: 3,
                    method: "GET",
                    name: "检修工单-列表-删除按钮",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/overhaulOrder",
                    viewPath: null,
                },
                {
                    code: "2005_btn_edit",
                    level: 3,
                    method: "GET",
                    name: "检修工单-列表-编辑按钮",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/overhaulOrder",
                    viewPath: null,
                },
                {
                    code: "2005_btn_finish",
                    level: 3,
                    method: "GET",
                    name: "检修工单-列表-结束按钮",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/overhaulOrder",
                    viewPath: null,
                },
                //现场勘查
                {
                    code: "2005_tab_surveyItem",
                    level: 3,
                    method: "GET",
                    name: "检修工单-关联现场勘查数据-查看权限",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/overhaulOrder",
                    viewPath: null,
                },
                //现场检修
                {
                    code: "2005_tab_siteOverhaul",
                    level: 3,
                    method: "GET",
                    name: "检修工单-现场检修",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/overhaulOrder",
                    viewPath: null,
                },
                {
                    code: "2005_siteOverhaul_appoint",
                    level: 3,
                    method: "GET",
                    name: "现场检修-工序指派按钮",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/overhaulOrder",
                    viewPath: null,
                },
                {
                    code: "2005_siteOverhaul_processInfo",
                    level: 3,
                    method: "GET",
                    name: "现场检修-工序信息查看",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/overhaulOrder",
                    viewPath: null,
                },
                {
                    code: "2005_siteOverhaul_workInfo_check",
                    level: 3,
                    method: "GET",
                    name: "现场检修-工序树-审核",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/overhaulOrder",
                    viewPath: null,
                },
                {
                    code: "2005_siteOverhaul_review",
                    level: 3,
                    method: "GET",
                    name: "现场检修-工序复核",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/overhaulOrder",
                    viewPath: null,
                }, {
                    code: "2005_siteOverhaul_addIssue",
                    level: 3,
                    method: "GET",
                    name: "现场检修-问题添加",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/overhaulOrder",
                    viewPath: null,
                }, {
                    code: "2005_siteOverhaul_editContent",
                    level: 3,
                    method: "GET",
                    name: "现场检修-工作内容编辑",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/overhaulOrder",
                    viewPath: null,
                },
                {
                    code: "2005_siteOverhaul_infoAppoint",
                    level: 3,
                    method: "GET",
                    name: "现场检修-派工按钮",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/overhaulOrder",
                    viewPath: null,
                },
                {
                    code: "2005_siteOverhaul_videoBind",
                    level: 3,
                    method: "GET",
                    name: "现场检修-视频绑定按钮",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/overhaulOrder",
                    viewPath: null,
                },
                {
                    code: "2005_siteOverhaul_orderCheck",
                    level: 3,
                    method: "GET",
                    name: "现场检修-复核人员按钮",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/overhaulOrder",
                    viewPath: null,
                },
                {
                    code: "2005_siteOverhaul_bigComponent",
                    level: 3,
                    method: "GET",
                    name: "现场检修-大件设备按钮",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/overhaulOrder",
                    viewPath: null,
                },
                {
                    code: "2005_siteOverhaul_issue",
                    level: 3,
                    method: "GET",
                    name: "现场检修-问题查看",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/overhaulOrder",
                    viewPath: null,
                },
                //报告：命名 2005_report_view|edit_报告的worktype
                {
                    code: "2005_report_view_2",
                    level: 3,
                    method: "GET",
                    name: "现场检修-施工方案-查看",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/overhaulOrder",
                    viewPath: null,
                }, {
                    code: "2005_report_edit_2",
                    level: 3,
                    method: "GET",
                    name: "现场检修-施工方案-编辑",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/overhaulOrder",
                    viewPath: null,
                },
                {
                    code: "2005_report_view_3",
                    level: 3,
                    method: "GET",
                    name: "现场检修-作业指导书-查看",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/overhaulOrder",
                    viewPath: null,
                }, {
                    code: "2005_report_edit_3",
                    level: 3,
                    method: "GET",
                    name: "现场检修-作业指导书-编辑",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/overhaulOrder",
                    viewPath: null,
                },
                {
                    code: "2005_report_view_4",
                    level: 3,
                    method: "GET",
                    name: "现场检修-试验报告-查看",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/overhaulOrder",
                    viewPath: null,
                }, {
                    code: "2005_report_edit_4",
                    level: 3,
                    method: "GET",
                    name: "现场检修-试验报告-编辑",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/overhaulOrder",
                    viewPath: null,
                },
                {
                    code: "2005_report_view_5",
                    level: 3,
                    method: "GET",
                    name: "现场检修-竣工报告-查看",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/overhaulOrder",
                    viewPath: null,
                }, {
                    code: "2005_report_edit_5",
                    level: 3,
                    method: "GET",
                    name: "现场检修-竣工报告-编辑",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/overhaulOrder",
                    viewPath: null,
                },
                //大件设备清单
                {
                    code: "2005_siteOverhaul_big_view",
                    level: 3,
                    method: "GET",
                    name: "现场检修-大件设备清单-查看",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/overhaulOrder",
                    viewPath: null,
                }, {
                    code: "2005_siteOverhaul_instrument_view",
                    level: 3,
                    method: "GET",
                    name: "现场检修-工器具清单-查看",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/overhaulOrder",
                    viewPath: null,
                }, {
                    code: "2005_siteOverhaul_instrument_edit",
                    level: 3,
                    method: "GET",
                    name: "现场检修-工器具清单-编辑",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/overhaulOrder",
                    viewPath: null,
                },{
                    code: "2005_siteOverhaul_materials_view",
                    level: 3,
                    method: "GET",
                    name: "现场检修-材料清单-查看",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/overhaulOrder",
                    viewPath: null,
                },{
                    code: "2005_siteOverhaul_materials_edit",
                    level: 3,
                    method: "GET",
                    name: "现场检修-材料清单-编辑",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/overhaulOrder",
                    viewPath: null,
                },
                {
                    code: "2005_siteOverhaul_videoMarker",
                    level: 3,
                    method: "GET",
                    name: "现场检修-录像标记",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/overhaulOrder",
                    viewPath: null,
                }, {
                    code: "2005_siteOverhaul_markerList_view",
                    level: 3,
                    method: "GET",
                    name: "现场检修-标记记录-查看",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/overhaulOrder",
                    viewPath: null,
                }, {
                    code: "2005_siteOverhaul_markerList_edit",
                    level: 3,
                    method: "GET",
                    name: "现场检修-标记记录-编辑",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/overhaulOrder",
                    viewPath: null,
                },
                //返厂检修-现场拆解
                {
                    code: "2005_tab_siteDismantle",
                    level: 3,
                    method: "GET",
                    name: "检修工单-现场拆解",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/overhaulOrder",
                    viewPath: null,
                },
                {
                    code: "2005_siteDismantle_appoint",
                    level: 3,
                    method: "GET",
                    name: "现场拆解-工序指派按钮",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/overhaulOrder",
                    viewPath: null,
                },
                {
                    code: "2005_siteDismantle_processInfo",
                    level: 3,
                    method: "GET",
                    name: "现场拆解-工序信息查看",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/overhaulOrder",
                    viewPath: null,
                },
                {
                    code: "2005_siteDismantle_workInfo_check",
                    level: 3,
                    method: "GET",
                    name: "现场拆解-工序树-审核",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/overhaulOrder",
                    viewPath: null,
                },
                {
                    code: "2005_siteDismantle_review",
                    level: 3,
                    method: "GET",
                    name: "现场拆解-工序复核",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/overhaulOrder",
                    viewPath: null,
                },
                {
                    code: "2005_siteDismantle_editContent",
                    level: 3,
                    method: "GET",
                    name: "现场拆解-工作内容编辑",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/overhaulOrder",
                    viewPath: null,
                },
                {
                    code: "2005_siteDismantle_addIssue",
                    level: 3,
                    method: "GET",
                    name: "现场拆解-问题添加",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/overhaulOrder",
                    viewPath: null,
                },
                {
                    code: "2005_siteDismantle_infoAppoint",
                    level: 3,
                    method: "GET",
                    name: "现场拆解-派工按钮",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/overhaulOrder",
                    viewPath: null,
                },
                {
                    code: "2005_siteDismantle_videoBind",
                    level: 3,
                    method: "GET",
                    name: "现场拆解-视频绑定按钮",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/overhaulOrder",
                    viewPath: null,
                },
                {
                    code: "2005_siteDismantle_orderCheck",
                    level: 3,
                    method: "GET",
                    name: "现场拆解-复核人员按钮",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/overhaulOrder",
                    viewPath: null,
                },
                {
                    code: "2005_siteDismantle_bigComponent",
                    level: 3,
                    method: "GET",
                    name: "现场拆解-大件设备按钮",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/overhaulOrder",
                    viewPath: null,
                },
                {
                    code: "2005_siteDismantle_issue",
                    level: 3,
                    method: "GET",
                    name: "现场拆解-问题查看",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/overhaulOrder",
                    viewPath: null,
                },
                //报告：命名 2005_report_view|edit_报告的worktype
                {
                    code: "2005_report_view_6",
                    level: 3,
                    method: "GET",
                    name: "现场拆解-施工方案-查看",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/overhaulOrder",
                    viewPath: null,
                }, {
                    code: "2005_report_edit_6",
                    level: 3,
                    method: "GET",
                    name: "现场拆解-施工方案-编辑",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/overhaulOrder",
                    viewPath: null,
                },
                {
                    code: "2005_report_view_7",
                    level: 3,
                    method: "GET",
                    name: "现场拆解-装运拆解作业指导书-查看",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/overhaulOrder",
                    viewPath: null,
                }, {
                    code: "2005_report_edit_7",
                    level: 3,
                    method: "GET",
                    name: "现场拆解-装运拆解作业指导书-编辑",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/overhaulOrder",
                    viewPath: null,
                },
                {
                    code: "2005_report_view_15",
                    level: 3,
                    method: "GET",
                    name: "现场拆解-现场拆解报告-查看",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/overhaulOrder",
                    viewPath: null,
                }, {
                    code: "2005_report_edit_15",
                    level: 3,
                    method: "GET",
                    name: "现场拆解-现场拆解报告-编辑",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/overhaulOrder",
                    viewPath: null,
                },
                //大件设备清单
                {
                    code: "2005_siteDismantle_big_view",
                    level: 3,
                    method: "GET",
                    name: "现场拆解-大件设备清单-查看",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/overhaulOrder",
                    viewPath: null,
                },
                 {
                    code: "2005_siteDismantle_instrument_view",
                    level: 3,
                    method: "GET",
                    name: "现场拆解-工器具清单-查看",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/overhaulOrder",
                    viewPath: null,
                }, {
                    code: "2005_siteDismantle_instrument_edit",
                    level: 3,
                    method: "GET",
                    name: "现场拆解-工器具清单-编辑",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/overhaulOrder",
                    viewPath: null,
                }, {
                    code: "2005_siteDismantle_materials_view",
                    level: 3,
                    method: "GET",
                    name: "现场拆解-材料清单-查看",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/overhaulOrder",
                    viewPath: null,
                },
                {
                    code: "2005_siteDismantle_materials_edit",
                    level: 3,
                    method: "GET",
                    name: "现场拆解-材料清单-编辑",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/overhaulOrder",
                    viewPath: null,
                },
                {
                    code: "2005_siteDismantle_bom_view",
                    level: 3,
                    method: "GET",
                    name: "现场拆解-拆解BOM-查看",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/overhaulOrder",
                    viewPath: null,
                },
                {
                    code: "2005_siteDismantle_bom_edit",
                    level: 3,
                    method: "GET",
                    name: "现场拆解-拆解BOM-编辑",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/overhaulOrder",
                    viewPath: null,
                },
                {
                    code: "2005_siteDismantle_returnList_view",
                    level: 3,
                    method: "GET",
                    name: "现场拆解-返厂清单-查看",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/overhaulOrder",
                    viewPath: null,
                },
                {
                    code: "2005_siteDismantle_returnList_download",
                    level: 3,
                    method: "GET",
                    name: "现场拆解-返厂清单-下载",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/overhaulOrder",
                    viewPath: null,
                }, {
                    code: "2005_siteDismantle_returnList_check",
                    level: 3,
                    method: "GET",
                    name: "现场拆解-返厂清单-复核",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/overhaulOrder",
                    viewPath: null,
                },
                {
                    code: "2005_siteDismantle_videoMarker",
                    level: 3,
                    method: "GET",
                    name: "现场拆解-录像标记",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/overhaulOrder",
                    viewPath: null,
                }, {
                    code: "2005_siteDismantle_markerList_view",
                    level: 3,
                    method: "GET",
                    name: "现场拆解-标记记录-查看",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/overhaulOrder",
                    viewPath: null,
                }, {
                    code: "2005_siteDismantle_markerList_edit",
                    level: 3,
                    method: "GET",
                    name: "现场拆解-标记记录-编辑",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/overhaulOrder",
                    viewPath: null,
                },
                //厂内拆解
                {
                    code: "2005_tab_factoryDismantle",
                    level: 3,
                    method: "GET",
                    name: "检修工单-厂内拆解",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/overhaulOrder",
                    viewPath: null,
                },
                {
                    code: "2005_factoryDismantle_appoint",
                    level: 3,
                    method: "GET",
                    name: "厂内拆解-工序指派按钮",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/overhaulOrder",
                    viewPath: null,
                },
                {
                    code: "2005_factoryDismantle_processInfo",
                    level: 3,
                    method: "GET",
                    name: "厂内拆解-工序信息查看",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/overhaulOrder",
                    viewPath: null,
                },
                {
                    code: "2005_factoryDismantle_workInfo_check",
                    level: 3,
                    method: "GET",
                    name: "厂内拆解-工序树-审核",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/overhaulOrder",
                    viewPath: null,
                },
                {
                    code: "2005_factoryDismantle_review",
                    level: 3,
                    method: "GET",
                    name: "厂内拆解-工序复核",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/overhaulOrder",
                    viewPath: null,
                }, {
                    code: "2005_factoryDismantle_addIssue",
                    level: 3,
                    method: "GET",
                    name: "厂内拆解-问题添加",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/overhaulOrder",
                    viewPath: null,
                },
                {
                    code: "2005_factoryDismantle_editContent",
                    level: 3,
                    method: "GET",
                    name: "厂内拆解-工作内容编辑",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/overhaulOrder",
                    viewPath: null,
                },
                {
                    code: "2005_factoryDismantle_infoAppoint",
                    level: 3,
                    method: "GET",
                    name: "厂内拆解-派工按钮",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/overhaulOrder",
                    viewPath: null,
                },
                {
                    code: "2005_factoryDismantle_videoBind",
                    level: 3,
                    method: "GET",
                    name: "厂内拆解-视频绑定按钮",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/overhaulOrder",
                    viewPath: null,
                },
                {
                    code: "2005_factoryDismantle_orderCheck",
                    level: 3,
                    method: "GET",
                    name: "厂内拆解-复核人员按钮",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/overhaulOrder",
                    viewPath: null,
                },
                {
                    code: "2005_factoryDismantle_issue",
                    level: 3,
                    method: "GET",
                    name: "厂内拆解-问题查看",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/overhaulOrder",
                    viewPath: null,
                },
                //报告：命名 2005_report_view|edit_报告的worktype
                {
                    code: "2005_report_view_8",
                    level: 3,
                    method: "GET",
                    name: "厂内拆解-作业指导书-查看",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/overhaulOrder",
                    viewPath: null,
                }, {
                    code: "2005_report_edit_8",
                    level: 3,
                    method: "GET",
                    name: "厂内拆解-作业指导书-编辑",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/overhaulOrder",
                    viewPath: null,
                },
                {
                    code: "2005_report_view_9",
                    level: 3,
                    method: "GET",
                    name: "厂内拆解-解体分析报告-查看",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/overhaulOrder",
                    viewPath: null,
                }, {
                    code: "2005_report_edit_9",
                    level: 3,
                    method: "GET",
                    name: "厂内拆解-解体分析报告-编辑",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/overhaulOrder",
                    viewPath: null,
                },
            
                {
                    code: "2005_factoryDismantle_bom_view",
                    level: 3,
                    method: "GET",
                    name: "厂内拆解-拆解BOM-查看",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/overhaulOrder",
                    viewPath: null,
                },
                {
                    code: "2005_factoryDismantle_bom_edit",
                    level: 3,
                    method: "GET",
                    name: "厂内拆解-拆解BOM-编辑",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/overhaulOrder",
                    viewPath: null,
                },
                {
                    code: "2005_factoryDismantle_videoMarker",
                    level: 3,
                    method: "GET",
                    name: "厂内拆解-录像标记",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/overhaulOrder",
                    viewPath: null,
                }, {
                    code: "2005_factoryDismantle_markerList_view",
                    level: 3,
                    method: "GET",
                    name: "厂内拆解-标记记录-查看",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/overhaulOrder",
                    viewPath: null,
                }, {
                    code: "2005_factoryDismantle_markerList_edit",
                    level: 3,
                    method: "GET",
                    name: "厂内拆解-标记记录-编辑",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/overhaulOrder",
                    viewPath: null,
                },
                //厂内生产
                {
                    code: "2005_tab_factoryCreate",
                    level: 3,
                    method: "GET",
                    name: "检修工单-厂内生产",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/overhaulOrder",
                    viewPath: null,
                },
                {
                    code: "2005_factoryCreate_appoint",
                    level: 3,
                    method: "GET",
                    name: "厂内生产-工序指派按钮",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/overhaulOrder",
                    viewPath: null,
                },
                {
                    code: "2005_factoryCreate_processInfo",
                    level: 3,
                    method: "GET",
                    name: "厂内生产-工序信息查看",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/overhaulOrder",
                    viewPath: null,
                },
                {
                    code: "2005_factoryCreate_workInfo_check",
                    level: 3,
                    method: "GET",
                    name: "厂内生产-工序树-审核",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/overhaulOrder",
                    viewPath: null,
                },
                {
                    code: "2005_factoryCreate_review",
                    level: 3,
                    method: "GET",
                    name: "厂内生产-工序复核",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/overhaulOrder",
                    viewPath: null,
                },{
                    code: "2005_factoryCreate_editContent",
                    level: 3,
                    method: "GET",
                    name: "厂内生产-工作内容编辑",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/overhaulOrder",
                    viewPath: null,
                }, {
                    code: "2005_factoryCreate_addIssue",
                    level: 3,
                    method: "GET",
                    name: "厂内生产-问题添加",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/overhaulOrder",
                    viewPath: null,
                },
                {
                    code: "2005_factoryCreate_infoAppoint",
                    level: 3,
                    method: "GET",
                    name: "厂内生产-派工按钮",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/overhaulOrder",
                    viewPath: null,
                },
                {
                    code: "2005_factoryCreate_videoBind",
                    level: 3,
                    method: "GET",
                    name: "厂内生产-视频绑定按钮",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/overhaulOrder",
                    viewPath: null,
                },
                {
                    code: "2005_factoryCreate_orderCheck",
                    level: 3,
                    method: "GET",
                    name: "厂内生产-复核人员按钮",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/overhaulOrder",
                    viewPath: null,
                },
                {
                    code: "2005_factoryCreate_issue",
                    level: 3,
                    method: "GET",
                    name: "厂内生产-问题查看",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/overhaulOrder",
                    viewPath: null,
                },
                //报告：命名 2005_report_view|edit_报告的worktype
                {
                    code: "2005_report_view_10",
                    level: 3,
                    method: "GET",
                    name: "厂内生产-作业指导书-查看",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/overhaulOrder",
                    viewPath: null,
                }, {
                    code: "2005_report_edit_10",
                    level: 3,
                    method: "GET",
                    name: "厂内生产-作业指导书-编辑",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/overhaulOrder",
                    viewPath: null,
                },
                {
                    code: "2005_report_view_11",
                    level: 3,
                    method: "GET",
                    name: "厂内生产-作业执行报告-查看",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/overhaulOrder",
                    viewPath: null,
                }, {
                    code: "2005_report_edit_11",
                    level: 3,
                    method: "GET",
                    name: "厂内生产-作业执行报告-编辑",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/overhaulOrder",
                    viewPath: null,
                },
            
                {
                    code: "2005_factoryCreate_bom_view",
                    level: 3,
                    method: "GET",
                    name: "厂内生产-厂内作业BOM-查看",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/overhaulOrder",
                    viewPath: null,
                },
                {
                    code: "2005_factoryCreate_bom_edit",
                    level: 3,
                    method: "GET",
                    name: "厂内生产-厂内作业BOM-编辑",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/overhaulOrder",
                    viewPath: null,
                },
                {
                    code: "2005_factoryCreate_videoMarker",
                    level: 3,
                    method: "GET",
                    name: "厂内生产-录像标记",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/overhaulOrder",
                    viewPath: null,
                }, {
                    code: "2005_factoryCreate_markerList_view",
                    level: 3,
                    method: "GET",
                    name: "厂内生产-标记记录-查看",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/overhaulOrder",
                    viewPath: null,
                }, {
                    code: "2005_factoryCreate_markerList_edit",
                    level: 3,
                    method: "GET",
                    name: "厂内生产-标记记录-编辑",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/overhaulOrder",
                    viewPath: null,
                },
                //试验
                {
                    code: "2005_tab_experiment",
                    level: 3,
                    method: "GET",
                    name: "检修工单-试验",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/overhaulOrder",
                    viewPath: null,
                },
                {
                    code: "2005_experiment_appoint",
                    level: 3,
                    method: "GET",
                    name: "试验-工序指派按钮",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/overhaulOrder",
                    viewPath: null,
                },
                {
                    code: "2005_experiment_processInfo",
                    level: 3,
                    method: "GET",
                    name: "试验-工序信息查看",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/overhaulOrder",
                    viewPath: null,
                },
                {
                    code: "2005_experiment_workInfo_check",
                    level: 3,
                    method: "GET",
                    name: "试验-工序树-审核",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/overhaulOrder",
                    viewPath: null,
                },
                {
                    code: "2005_experiment_review",
                    level: 3,
                    method: "GET",
                    name: "试验-工序复核",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/overhaulOrder",
                    viewPath: null,
                }, {
                    code: "2005_experiment_editContent",
                    level: 3,
                    method: "GET",
                    name: "试验-工作内容编辑",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/overhaulOrder",
                    viewPath: null,
                }, {
                    code: "2005_experiment_addIssue",
                    level: 3,
                    method: "GET",
                    name: "试验-问题添加",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/overhaulOrder",
                    viewPath: null,
                },
                {
                    code: "2005_experiment_infoAppoint",
                    level: 3,
                    method: "GET",
                    name: "试验-派工按钮",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/overhaulOrder",
                    viewPath: null,
                },
                {
                    code: "2005_experiment_videoBind",
                    level: 3,
                    method: "GET",
                    name: "试验-视频绑定按钮",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/overhaulOrder",
                    viewPath: null,
                },
                {
                    code: "2005_experiment_orderCheck",
                    level: 3,
                    method: "GET",
                    name: "试验-复核人员按钮",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/overhaulOrder",
                    viewPath: null,
                },
                {
                    code: "2005_experiment_issue",
                    level: 3,
                    method: "GET",
                    name: "试验-问题查看",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/overhaulOrder",
                    viewPath: null,
                },
                //报告：命名 2005_report_view|edit_报告的worktype
                {
                    code: "2005_report_view_12",
                    level: 3,
                    method: "GET",
                    name: "试验-作业指导书-查看",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/overhaulOrder",
                    viewPath: null,
                }, {
                    code: "2005_report_edit_12",
                    level: 3,
                    method: "GET",
                    name: "试验-作业指导书-编辑",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/overhaulOrder",
                    viewPath: null,
                },
                {
                    code: "2005_report_view_13",
                    level: 3,
                    method: "GET",
                    name: "试验-试验报告-查看",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/overhaulOrder",
                    viewPath: null,
                }, {
                    code: "2005_report_edit_13",
                    level: 3,
                    method: "GET",
                    name: "试验-试验报告-编辑",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/overhaulOrder",
                    viewPath: null,
                },
                {
                    code: "2005_experiment_videoMarker",
                    level: 3,
                    method: "GET",
                    name: "试验-录像标记",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/overhaulOrder",
                    viewPath: null,
                }, {
                    code: "2005_experiment_markerList_view",
                    level: 3,
                    method: "GET",
                    name: "试验-标记记录-查看",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/overhaulOrder",
                    viewPath: null,
                }, {
                    code: "2005_experiment_markerList_edit",
                    level: 3,
                    method: "GET",
                    name: "试验-标记记录-编辑",
                    showOrder: null,
                    sub: [],
                    type: 2,
                    url: "/overhaul/overhaulOrder",
                    viewPath: null,
                },
            ],
            type: 1,
            url: "/overhaul/overhaulOrder",
            viewPath: null
        },
        {
            code: "2006_log",
            level: 2,
            method: "GET",
            name: "日志管理",
            showOrder: null,
            sub: [
                {
                    code: "200601_operation",
                    level: 3,
                    method: "GET",
                    name: "操作日志",
                    showOrder: null,
                    sub: [],
                    type: 1,
                    url: "/overhaul/log/operation",
                    viewPath: null
                },
                {
                    code: "200602_clockIn",
                    level: 3,
                    method: "GET",
                    name: "打卡日志",
                    showOrder: null,
                    sub: [],
                    type: 1,
                    url: "/overhaul/log/clockIn",
                    viewPath: null
                }],
            type: 1,
            url: "/overhaul/log",
            viewPath: null
        },
        {
            code: "2007_profile",
            level: 2,
            method: "GET",
            name: "个人中心",
            showOrder: null,
            sub: [
                {
                    code: "200701_myNotice",
                    level: 3,
                    method: "GET",
                    name: "我的通知",
                    showOrder: null,
                    sub: [],
                    type: 1,
                    url: "/overhaul/profile/myNotice",
                    viewPath: null
                },
                {
                    code: "200702_myTask",
                    level: 3,
                    method: "GET",
                    name: "我的任务",
                    showOrder: null,
                    sub: [],
                    type: 1,
                    url: "/overhaul/profile/myTask",
                    viewPath: null
                }],
            type: 1,
            url: "/overhaul/profile",
            viewPath: null
        }, {
            code: "2008_problemLib",
            level: 2,
            method: "GET",
            name: "检修问题库",
            showOrder: null,
            sub: [],
            type: 1,
            url: "/overhaul/problemLib",
            viewPath: null
        }
    ],
    type: 1,
    url: "/overhaul",
    viewPath: null,
}